name: download_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
# For downloader
  flutter_downloader: ^1.10.1+2
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  sqflite: ^2.2.4+1
  path: ^1.8.2
  get_storage: ^2.0.3

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

